// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = " YOUR DEVICE ID ";

const char SSID[]               = "YOUR WIFI NAME";    // Network SSID (name)
const char PASS[]               = "YOUR WIFI-PASS";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "YOUR SECRET KEY";    // Secret device password

void onSwitch1Change();
void onSwitch2Change();
void onSwitch3Change();
void onSwitch4Change();

bool switch1;
bool switch2;
bool switch3;
bool switch4;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(switch1, READWRITE, ON_CHANGE, onSwitch1Change);
  ArduinoCloud.addProperty(switch2, READWRITE, ON_CHANGE, onSwitch2Change);
  ArduinoCloud.addProperty(switch3, READWRITE, ON_CHANGE, onSwitch3Change);
  ArduinoCloud.addProperty(switch4, READWRITE, ON_CHANGE, onSwitch4Change);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);


void setup() {
  pinMode(D1,OUTPUT);
  pinMode(D2,OUTPUT);
  pinMode(D3,OUTPUT);
  pinMode(D4,OUTPUT);
  
  Serial.begin(9600);
    if (WiFi.status() == WL_CONNECTED) {
    Serial.println("Disconnecting from Wi-Fi...");
    WiFi.disconnect();
  }

  // Connect to Wi-Fi
  Serial.println("Connecting to Wi-Fi...");
  WiFi.begin(SSID, PASS);

  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }

  Serial.println("");
  Serial.println("WiFi connected");
  Serial.print("IP address: ");
  Serial.println(WiFi.localIP());
  delay(500); 
  initProperties();

  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  
  
}
void onSwitch1Change()  {
  if (switch1)
  {
    digitalWrite(D1,LOW);
    
  }
  else
  {
    digitalWrite(D1,HIGH);
  }
  
}
void onSwitch2Change()  {
  if (switch2)
  {
    digitalWrite(D2,LOW);
  }
  else
  {
    digitalWrite(D2,HIGH);
  }
  
}
void onSwitch3Change()  {
  if (switch3)
  {
    digitalWrite(D3,LOW);
    
  }
  else
  {
    digitalWrite(D3,HIGH);
  }
}
void onSwitch4Change()  {
  if (switch4)
  {
    digitalWrite(D4,LOW);
  }
  else
  {
    digitalWrite(D4,HIGH);
  }
} 
