// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "74c7e7d3-b250-442b-bf6a-1d68d3c08994";

const char SSID[]               = "Tj-mobile";    // Network SSID (name)
const char PASS[]               = "12345678";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "ERKVODGYQYI4AN5CCELR";    // Secret device password

void onAutomanChange();
void onMainChange();
void onSwitch1Change();
void onSwitch2Change();
void onSwitch3Change();

bool automan;
bool mainswitch;
bool switch1;
bool switch2;
bool switch3;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(automan, READWRITE, ON_CHANGE, onAutomanChange);
  ArduinoCloud.addProperty(mainswitch, READWRITE, ON_CHANGE, onMainChange);
  ArduinoCloud.addProperty(switch1, READWRITE, ON_CHANGE, onSwitch1Change);
  ArduinoCloud.addProperty(switch2, READWRITE, ON_CHANGE, onSwitch2Change);
  ArduinoCloud.addProperty(switch3, READWRITE, ON_CHANGE, onSwitch3Change);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);

void setup() {
  // Initialize serial and wait for port to open:
  pinMode(D0,OUTPUT);
  pinMode(D1,OUTPUT);
  pinMode(D2,OUTPUT);
  Serial.begin(9600);
    if (WiFi.status() == WL_CONNECTED) {
    Serial.println("Disconnecting from Wi-Fi...");
    WiFi.disconnect();
  }
  // Connect to Wi-Fi
  Serial.println("Connecting to Wi-Fi...");
  WiFi.begin(SSID, PASS);
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
  Serial.println("");
  Serial.println("WiFi connected");
  Serial.print("IP address: ");
  Serial.println(WiFi.localIP());
  delay(100); 
  // Defined in thingProperties.h
  initProperties();
  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}
void loop() {
  ArduinoCloud.update();
  // Your code here  
  int ldrdata = analogRead(A0);
  Serial.println(ldrdata);
  if(mainswitch==false){
  if(ldrdata<300){
      digitalWrite(D0,HIGH);
      digitalWrite(D1,HIGH);
      digitalWrite(D2,HIGH);
    }
  }
}
void onAutomanChange()  {
  // Add your code here to act upon Automan change
  // if (automan){
  //   mainswitch= true;
  // }
  // else{
  //   mainswitch= false;
  // }
}
void onMainChange()  {
  // Add your code here to act upon Main change
  if(mainswitch){
    switch1= true;
    switch2= true;
    switch3= true;
  }
}
void onSwitch1Change()  {
  // Add your code here to act upon Switch1 change
  if(switch1){
    digitalWrite(D0,HIGH);
  }
}
void onSwitch2Change()  {
  // Add your code here to act upon Switch2 change
    if(switch2){
    digitalWrite(D1,HIGH);
  }
}
void onSwitch3Change()  {
  // Add your code here to act upon Switch3 change
    if(switch3){
    digitalWrite(D3,HIGH);
  }
}